spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank Acounts related Apis"
  contactDetails:
    name: "hrishi"
    email: "hrishikeshshedge@gmail.com"
  onCallSupport:
    - (555)555-333
    - (555)555-112

  application:
    name: account