spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to Bank Cards related Apis"
  contactDetails:
    name: "saloni"
    email: "salonisingh@gmail.com"
  onCallSupport:
    - (555)555-712
    - (555)555-337